Pedidos Web/Pedidos Web/Models/Pedido.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pedidos_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.Auditorias = new HashSet<Auditoria>();
            this.Detalles = new HashSet<Detalle>();
        }
    
        public int id_pedido { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public int id_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auditoria> Auditorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle> Detalles { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Usuario Cliente { get; set; }
        public virtual Usuario Empleado { get; set; }
    }
}

Pedidos Web/Pedidos Web/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Pedidos_Web.Models;

namespace Pedidos_Web.Controllers
{
    public class PedidosController : BaseController
    {
        private PedidosWebEntities db = new PedidosWebEntities();
        
        // GET: Pedidos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedidos = db.Pedidos.Find(id);
            if (pedidos == null)
            {
                return HttpNotFound();
            }
            return View(pedidos);
        }

        // GET: Pedidos/Create
        public ActionResult Create()
        {
            Estado e = db.Estados.Find(1); //Pedido nuevo
            Pedido nuevoPedido = new Pedido()
            {
                Cliente = usuarioActual,
                Estado = e
            };


            Session["pedido"] = nuevoPedido;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id_Menu, Descripcion, precio, cantidad")] Menue menu)
        public ActionResult Create([Bind(Include = "Id_Menu, Cantidad")] Menu menu)
        {

            string cantidad = Request.Form["cant"];
            string id_menu = Request.Form["id_menu"];

            //Validaciones
            //que el ID exista: ir a la base y traer el menu cuyo ID sea el que viene por post
            Menu _menu = db.Menus.Find(Convert.ToInt16(id_menu));
            if (_menu == null)
            {
                return RedirectToAction("Create");
                //return HttpNotFound();
            }

            //que el numero sea > 0
            int cant = Int16.Parse(cantidad);
            if (cant <= 0)
            {
                return RedirectToAction("Create");

            }

            //que haya suficiente stock
            //_menu.stock >= cantidad
            if (cant > _menu.stock)
            {
                return RedirectToAction("Create");
            }

            Pedido p = new Pedido();
            //Cargar el nuevo objeto pedido
            //p.id_menu = _menu.id_menu;
            //            p.precio_unitario = _menu.precio;
            //p.cantidad = cant;
            //p.id_cliente = 
            //p.id_empleado = 
            //          p.fecha_alta = DateTime;
            p.fecha_entrega = null;
            //p.id_estado = 0;

            if (ModelState.IsValid)
            {
                db.Pedidos.Add(p);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(menu);

        }


        // GET: Pedidos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = db.Pedidos.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_estado = new SelectList(db.Estados, "id_estado", "descripcion", pedido.id_estado);
            //ViewBag.id_menu = new SelectList(db.Menus, "id_menu", "titulo", pedido.id_menu);
            ViewBag.id_cliente = new SelectList(db.Usuarios, "id_usuario", "apellido", pedido.id_cliente);
            ViewBag.id_empleado = new SelectList(db.Usuarios, "id_usuario", "apellido", pedido.id_empleado);
            return View(pedido);
        }

        // POST: Pedidos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_pedido,id_menu,precio_unitario,cantidad,id_cliente,id_empleado,fecha_alta,fecha_entrega,id_estado")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pedido).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            ViewBag.id_estado = new SelectList(db.Estados, "id_estado", "descripcion", pedido.id_estado);
            //ViewBag.id_menu = new SelectList(db.Menus, "id_menu", "titulo", pedido.id_menu);
            ViewBag.id_cliente = new SelectList(db.Usuarios, "id_usuario", "apellido", pedido.id_cliente);
            ViewBag.id_empleado = new SelectList(db.Usuarios, "id_usuario", "apellido", pedido.id_empleado);
            return View(pedido);
        }

        [HttpPost]
        public JsonResult ActualizarPedido()
        {
            bool resultado = true;
            string mensaje = "";

            string id_menu = Request.Form["id_menu"];
            string cantidad = Request.Form["cant"];

            Menu m = db.Menus.Find(id_menu);

            //Stock > 0
            if (Convert.ToInt64(cantidad) < 1)
            {
                resultado = false;
                mensaje = "La cantidad ingresada es invalida.";
                return Json(new { message = mensaje, success = resultado });
            }

            //Validar si hay stock
            if (m.stock < Convert.ToInt64(cantidad))
            {
                resultado = false;
                mensaje = "No hay suficiente stock para abastecer el pedido del menú seleccionado.";
                return Json(new { message = mensaje, success = resultado });
            }

            Pedido p = Session["pedido"] as Pedido;
            Detalle d = new Detalle()
            {
                id_menu = m.id_menu,
                cantidad = Convert.ToInt32(cantidad),
                precio_unitario = m.precio ?? 0
            };
            



            return Json(new { message = "", success = true });
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Pedidos Web/Pedidos Web/Views/Pedidos/Create.cshtml
@using Pedidos_Web.Models

@{
    ViewBag.Title = "Nuevo Pedido";
    Layout = "~/Views/Shared/_Layout.cshtml";
    PedidosWebEntities db = new PedidosWebEntities();
    IEnumerable<Menu> menues = db.Menus.ToList();
    Pedido p = Session["pedido"] as Pedido;
    string cliente = p.Cliente.apellido + ", " + p.Cliente.nombre;
}

<h2>Nuevo Pedido</h2>


@using (Html.BeginForm())
{
    @Html.Hidden("id_menu")
    @Html.Hidden("cant")

    <div class="form-horizontal col-xs-8 col-sm-offset-2">

        <h3>@cliente</h3>
        <h5>Estado del pedido: @p.Estado.descripcion</h5>
        <hr />
        <h2>DETALLE</h2>
        <table class="table">
            <tr>
                <th class="hidden">
                    @Html.DisplayName("ID Menu")
                </th>
                <th>
                    @Html.DisplayName("Descripcion")
                </th>
                <th>
                    @Html.DisplayName("Precio")
                </th>
                <th>
                    @Html.DisplayName("Cantidad")
                </th>
            </tr>
            @foreach (Menu item in menues)
            {
                <tr>
                    <td class="hidden">
                        @Html.DisplayFor(ModelItem => item.id_menu)
                    </td>
                    <td>
                        @Html.DisplayFor(ModelItem => item.descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(ModelItem => item.precio)
                    </td>
                    <td>
                        <input type="number" name="cantidad" value="cantidad" />
                        <input type="submit" value="Agregar" id="agregar" />
                    </td>
                </tr>

            }

        </table>

    </div>
}
            </div>
@section Scripts {

    <script>

        $(document).ready(function () {
            $('#agregar').click(function (e) {
                e.preventDefault();
                var celda = $(this).parent(); //celda (td)
                var linea = celda.parent(); //linea (tr)

                $('#id_menu').val($.trim(linea[0].children[0].innerText));
                $('#cant').val(linea[0].children[3].children[0].value);
                var request = $('form').serialize();
                //$('form').submit();

                $.post('@Url.Action("ActualizarPedido", "Pedidos")',
                    request,
                    function (data) {
                        if (!data.success)
                            alert(data.message);
                    });



            });

        });

    </script>


}

Pedidos Web/Pedidos Web/Views/Pedidos/Details.cshtml
@model Pedidos_Web.Models.Pedido

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_pedido }) |
    @Html.ActionLink("Back to List", "Index", "Home")
</p>

Pedidos Web/Pedidos Web/Views/Pedidos/Edit.cshtml
@model Pedidos_Web.Models.Pedido

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Pedidos Web/Pedidos Web/Views/Pedidos/View.cshtml
@model Pedidos_Web.Models.Pedido


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pedido</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id_menu, "id_menu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_menu", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_menu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio_unitario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio_unitario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio_unitario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_cliente, "id_cliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_cliente", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_cliente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_empleado, "id_empleado", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_empleado", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_empleado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha_alta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha_alta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha_alta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha_entrega, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha_entrega, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha_entrega, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_estado, "id_estado", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_estado", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}