Comidator/Controllers/Tipos_IngredienteController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Comidator.Models;

namespace Comidator.Controllers
{
    public class Tipos_IngredienteController : Controller
    {
        private COMIDATOREntities db = new COMIDATOREntities();

        public ActionResult Index()
        {
            var tipos_Ingrediente = db.Tipos_Ingrediente.Include(t => t.Ingrediente);
            return View(tipos_Ingrediente.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tipos_Ingrediente tipos_Ingrediente = db.Tipos_Ingrediente.Find(id);
            if (tipos_Ingrediente == null)
            {
                return HttpNotFound();
            }
            return View(tipos_Ingrediente);
        }

        public ActionResult Create()
        {
            ViewBag.id = new SelectList(db.Ingredientes, "id", "descripcion");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tipos_Ingrediente tipos_Ingrediente)
        {
            if (ModelState.IsValid)
            {
                db.Tipos_Ingrediente.Add(tipos_Ingrediente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id = new SelectList(db.Ingredientes, "id", "descripcion", tipos_Ingrediente.id);
            return View(tipos_Ingrediente);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tipos_Ingrediente tipos_Ingrediente = db.Tipos_Ingrediente.Find(id);
            if (tipos_Ingrediente == null)
            {
                return HttpNotFound();
            }
            ViewBag.id = new SelectList(db.Ingredientes, "id", "descripcion", tipos_Ingrediente.id);
            return View(tipos_Ingrediente);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Tipos_Ingrediente tipos_Ingrediente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipos_Ingrediente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id = new SelectList(db.Ingredientes, "id", "descripcion", tipos_Ingrediente.id);
            return View(tipos_Ingrediente);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tipos_Ingrediente tipos_Ingrediente = db.Tipos_Ingrediente.Find(id);
            if (tipos_Ingrediente == null)
            {
                return HttpNotFound();
            }
            return View(tipos_Ingrediente);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tipos_Ingrediente tipos_Ingrediente = db.Tipos_Ingrediente.Find(id);
            db.Tipos_Ingrediente.Remove(tipos_Ingrediente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Comidator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Comidator</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Comidator", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Usuarios", "Index", "Usuarios")</li>
                    <li>@Html.ActionLink("Tipos de Ingrediente", "Index", "Tipos_Ingrediente")</li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>